name: reply_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_speed_dial: ^1.2.5
  material_about: ^0.2.1
  share: '>=0.6.4+2 <2.0.0'
  url_launcher: ^5.0.5
  provider: ^4.3.2+2
  firebase_core: "^0.5.0"
  firebase_auth: "^0.18.0+1"
  cloud_firestore: "^0.14.0+2"
  google_sign_in: ^4.5.4
  flutter_local_notifications: ^1.4.4+1
  rxdart: ^0.24.1
  apple_sign_in: ^0.1.0
  flutter_secure_storage: ^3.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
 uses-material-design: true
 assets:
 - images/
 fonts:
 - family: Roboto
   fonts:
     - asset: fonts/Roboto-Light.ttf
